[2024-11-02T02:46:54.047+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-02T02:46:54.065+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: predictive_maintenance_pipeline.train_best_model_bin manual__2024-11-02T02:46:41.499581+00:00 [queued]>
[2024-11-02T02:46:54.074+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: predictive_maintenance_pipeline.train_best_model_bin manual__2024-11-02T02:46:41.499581+00:00 [queued]>
[2024-11-02T02:46:54.075+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-11-02T02:46:54.110+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): train_best_model_bin> on 2024-11-02 02:46:41.499581+00:00
[2024-11-02T02:46:54.148+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=77) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-02T02:46:54.149+0000] {standard_task_runner.py:72} INFO - Started process 78 to run task
[2024-11-02T02:46:54.150+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'predictive_maintenance_pipeline', 'train_best_model_bin', 'manual__2024-11-02T02:46:41.499581+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/mlops_version_py.py', '--cfg-path', '/tmp/tmp5oi4k6q4']
[2024-11-02T02:46:54.151+0000] {standard_task_runner.py:105} INFO - Job 28: Subtask train_best_model_bin
[2024-11-02T02:46:54.258+0000] {task_command.py:467} INFO - Running <TaskInstance: predictive_maintenance_pipeline.train_best_model_bin manual__2024-11-02T02:46:41.499581+00:00 [running]> on host 1dda86545537
[2024-11-02T02:46:54.362+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='predictive_maintenance_pipeline' AIRFLOW_CTX_TASK_ID='train_best_model_bin' AIRFLOW_CTX_EXECUTION_DATE='2024-11-02T02:46:41.499581+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-02T02:46:41.499581+00:00'
[2024-11-02T02:46:54.363+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-02T02:46:55.716+0000] {logging_mixin.py:190} INFO - Searching best binary model
[2024-11-02T02:46:55.722+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/joblib/parallel.py:1359: UserWarning: Loky-backed parallel loops cannot be called in a multiprocessing, setting n_jobs=1
  n_jobs = self._backend.configure(n_jobs=self.n_jobs, parallel=self,

[2024-11-02T02:46:55.962+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/joblib/parallel.py:1359: UserWarning: Loky-backed parallel loops cannot be called in a multiprocessing, setting n_jobs=1
  n_jobs = self._backend.configure(n_jobs=self.n_jobs, parallel=self,

[2024-11-02T02:46:56.113+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/joblib/parallel.py:1359: UserWarning: Loky-backed parallel loops cannot be called in a multiprocessing, setting n_jobs=1
  n_jobs = self._backend.configure(n_jobs=self.n_jobs, parallel=self,

[2024-11-02T02:46:56.268+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/joblib/parallel.py:1359: UserWarning: Loky-backed parallel loops cannot be called in a multiprocessing, setting n_jobs=1
  n_jobs = self._backend.configure(n_jobs=self.n_jobs, parallel=self,

[2024-11-02T02:46:58.674+0000] {logging_mixin.py:190} INFO - Best model found: RandomForestClassifier(class_weight={0: 0.697901, 1: 11.955361})
[2024-11-02T02:46:59.320+0000] {logging_mixin.py:190} INFO - Model trained and saved
[2024-11-02T02:46:59.320+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-11-02T02:46:59.329+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-02T02:46:59.330+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=predictive_maintenance_pipeline, task_id=train_best_model_bin, run_id=manual__2024-11-02T02:46:41.499581+00:00, execution_date=20241102T024641, start_date=20241102T024654, end_date=20241102T024659
[2024-11-02T02:46:59.388+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-02T02:46:59.414+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-11-02T02:46:59.418+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
